name: Trigger Database Update in Core Repo

on:
  workflow_dispatch:
    inputs:
      sdk_tag:
        type: string
        description: Provide the SDK release tag
        default: "mikroSDK-2.13.1"
      database_version:
        type: choice
        description: Database version to update
        options:
          - Test
          - Live

jobs:
  trigger_db_update:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - name: Trigger Database update in Core repo
        run: |
          # Set the required variables
          repo_owner="MikroElektronika"
          repo_name="core_packages"
          event_type="trigger-workflow"
          version="${{ github.event.inputs.sdk_tag }}"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MIKROE_ACTIONS_KEY }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"version\": \"$version\", \"index\": \"${{ github.event.inputs.database_version }}\", \"unit\": false, \"integration\": true}}"
